/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/large-asteroid-small-moon-free-97e836948dd14a5ba4ed69ff8d0d0831
Title: Large Asteroid / Small Moon (FREE)
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    PlanetMat: THREE.MeshPhysicalMaterial
  }
}

export function Asteroid(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/asteroid.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.PlanetMat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/asteroid.glb')