/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/astronaut-rigged-and-animated-f45039084a674080b42f5e171fd4f04c
Title: Astronaut rigged and animated
*/

import * as THREE from 'three'
import { useRef, useEffect, type JSX } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    Object_9: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    bake_1: THREE.MeshStandardMaterial
    bake_2: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Astronaut(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(
    'models/astronaut.glb'
  ) as unknown as GLTFResult
  const { actions } = useAnimations(animations as unknown as THREE.AnimationClip[], group)

  useEffect(() => {
    actions?.['astro_bones|idle_1']?.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="e952fa4833e348ad9d5195d3a7080abbfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="suit_low_poly" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="astro_bones" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.bake_1}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.bake_2}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/astronaut.glb')
