/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DGB (https://sketchfab.com/peer123)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/earth-our-fragile-home-de97ac7081cd443584c4707efd14725a
Title: Earth: Our Fragile Home
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";

type GLTFResult = {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Earth(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("models/earth.glb") as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" position={[0, 0.987, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/earth.glb");
