/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/space-satellite-4e6485de34914ba4a493211f33616182
Title: Space Satellite
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    Satellite: THREE.MeshStandardMaterial
    Satellite2: THREE.MeshStandardMaterial
  }
}

export function SpaceSatelite(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/space_satellite.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Satellite} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Satellite2} />
      </group>
    </group>
  )
}

useGLTF.preload('models/space_satellite.glb')